### ISSUE TITLE
Create Colab Notebook from .py file

### ISSUE THREAD

**Issue by Abhinandan-Pal** [DSC-IIIT-Kalyani/Pandemic-Simulator#6]
Create a Colab notebook for the Sim_centered.py . Running the whole python file at once can be really messy. And few of the steps are rather time-consuming. A better alternative would be implementing them on Colab. One of the .py file has been worked out for reference. 

.py file : [Link](https://github.com/DSC-IIIT-Kalyani/Pandemic-Simulator/blob/master/Mutiple_community/Multi_comm2.py)

Colab notebook : [Link](https://github.com/DSC-IIIT-Kalyani/Pandemic-Simulator/blob/master/Mutiple_community/Pandemic_Simulator(Mulltiple__community).ipynb)

**Comment by Siddhant-K-code** [comment]
i can work on this

**Comment by Siddhant-K-code** [comment]
Getting This Error in Colab!

![image](https://user-images.githubusercontent.com/55068936/102846348-c42a6400-4435-11eb-9fd1-533fdb3a6014.png)

Even Original `.py` File Has Same Error

![image](https://user-images.githubusercontent.com/55068936/102846143-3e0e1d80-4435-11eb-9947-da270c78a609.png)

**Comment by Abhinandan-Pal** [comment]
Apologies for the error it has been fixed.

**Comment by Siddhant-K-code** [comment]
but, error was in `Pandemic-Simulator/With Landmark/Sim_centered.py `

**Comment by Siddhant-K-code** [comment]
@Abhinandan-Pal Please review PR #9
